/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.jetbrains.dokka")
    id("de.jfachwert.java-conventions")
}

dependencies {
    api(project(":core"))
    testImplementation(project(":test"))
}

description = "formular"
