/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.jetbrains.dokka")
    id("de.jfachwert.java-conventions")
}

dependencies {
    api(project(":core"))
    api(project(":math"))
    implementation("javax.money:money-api:1.1")
    testImplementation(project(":money"))
    testImplementation(project(":test"))
}

description = "bank"
