[[section-building-block-view]]


== Bausteinsicht



=== Whitebox Gesamtsystem

["plantuml", "packages", "svg"]
------------------------------------------------
include::../images/packages.puml[]
------------------------------------------------

Enthaltene Bausteine::

Die einzelnen Klassen sind in fachliche Packages aufgeteilt.

.Packages
[cols="1,4" options="header"]
|===
|Package |Beschreibung

|bank
|alles, was mit Banken zu tun hat wie `IBAN`, `BIC` oder `Kontonummer`

|steuer
|das Finanzamt lässt grüßen - hier sind Fachwerte wie `Steuernummer` und `UStIdNr` defniert

|post
|hier finden sich Fachwerte wie `Anschrift`, `Adresse` oder `PLZ`

|rechnung
|Fachwerte, die man üblicherweise auf Rechnungen antrifft wie `Bestellnummer`, `Referenznummer` oder `Rechnungsmonat`

|net
|Fachwerte für das Neuland "Internet" wie `EMailAdresse` oder `Domainname`
|===

Das pruefung-Package enthält Klassen zur Validierung und zu verschiedenen Pruefzifferverfahren.
So enthalten manche Fachwerte wie `IBAN` eine Pruefziffer, um Fehleingaben zu erkennen.


Wichtige Schnittstellen::
Jede Klasse hat einen Konstruktor, über den ein Objekt davon angelegt wird.
Es gibt keine Setter-Methoden, da die Klasse immutable ist.


==== bank

["plantuml", "packages", "svg"]
------------------------------------------------
include::../images/package-bank.puml[]
------------------------------------------------

Mit dem bank-Package hat alles angefangen.
Die Fachwerte in diesem Paket repräsentieren Konzepte, die im Bank-Umfeld typischerweise anzutreffen sind.



==== <Name Blackbox 2>

_<Blackbox-Template>_

==== <Name Blackbox n>

_<Blackbox-Template>_


==== <Name Schnittstelle 1>

...

==== <Name Schnittstelle m>



=== Ebene 2



==== Whitebox _<Baustein 1>_



_<Whitebox-Template>_

==== Whitebox _<Baustein 2>_


_<Whitebox-Template>_

...

==== Whitebox _<Baustein m>_


_<Whitebox-Template>_



=== Ebene 3




==== Whitebox <_Baustein x.1_>




_<Whitebox-Template>_


==== Whitebox <_Baustein x.2_>

_<Whitebox-Template>_



==== Whitebox <_Baustein y.1_>

_<Whitebox-Template>_
