[[section-design-decisions]]

== Entwurfsentscheidungen


=== Keine `null`-Werte

Ein Grund für die Migration auf Kotlin war die Unterbindung von null-Werten.
Damit kann schon auf Aufruf-Ebene garantiert werden, dass null-Werte nicht weitergegeben werden, sondern sofort zum Fehler führen ("fail fast").


=== NULL-Konstanten

Mit v2.2 wurden NULL-Konstanten eingeführt.
Damit können Variablen mit diesem Wert vorbelegt werden.


=== Kein Logging / Minimale Abhängigkeiten

Um nicht von einem bestimmten Log-Framework abhängig zu sein, wird auf Logging weitgehend verzichtet.
Das bedeutet, dass in einem Falle eines Fehlers oder fehlerhaften Aufrufs eine hilfreiche Exception ausgelöst wird.
Diese Exception stellt alle Informationen zur Verfügung, um die Ursache des Fehlers zu finden.
Exceptions, die abgefangen und behandelt werden, werden ueber das Logging-Framework des JDKs protokolliert.
Um diese Meldungen sichtbar zu machen, muss der Log-Level FINE oder FINER (für den Stacktrace) konfiguriert werden.

Um sich nicht weitere unerwünschte Abhängigkeiten bei der Verwendung von jFachwert einzufangen, werden die Abhängigkeiten zu anderen Bibiotheken auf ein Minimum reduziert.
Die einzigen Abhängigkeiten, die in Kauf genommen werden, sind:

* kotlin-stdlib: diese Bibliothek kam durch die Umstellung auf Kotlin in v4 hinzu
* commons-lang3: diese Bibliothek ist bereits als Abhängigkeit vieler anderer Bibliotheken vorhanden
* validation-api: Basis-Bibliothek für Validierung (nur bis v5)
* money-api (JSR 354): diese API sowie einige weitere Bibliotheken sollten ab Java 9 Bestandteil des JDKs sein.
  Tatsächlich müssen sie immer noch als Dependency aufgeführt werden.
  Deswegen wurde mit v6 die Bibliothek in verschiedene Unterbibliotheken aufgeilt.
  Damit kann diese API-Lib weggelassen werden, wenn kein Umgang mit Geldbeträgen benötigt wird.

Mit v4.4 wurde die Abhänigkeit zu commons-text und commons-collections4 wieder entfernt, da Kotlin hierfür genügend Unterstützung anbietet, um die fehlende Funktionalität selbst zu implementieren.
Auch wurde die `ValidationException` aus der validation-api-Bibliothek durch eine gleichnamige Exception aus `de.jfachwert.pruefung.exception` ersetzt, um die Abhängigkeit zu JavaEE zu vermeiden.
Andernfalls hätte diese Abhängigkeit auf JakartaEE geändert werden müssen.


=== Ableitung möglich

Um für Fachklassen auch eigene Logik hinterlegen zu können, können die Klassen abgeleitet werden.
Deswegen sind die Klassen nicht `final`.


=== Konstruktor mit Validierung

Jede Klasse besitzt einen Konstruktor, der als letztes Argument einen Validator (z.B. in Form eines Pruefzifferverfahrens) hat.
Damit ist sichergestellt, dass

* nur gültige Fachwerte erzeugt werden können,
* der Validator von der abgeleiteten Klasse ver- oder entschärft werden kann (je nach Anforderung).



=== Minimaler Footprint

Mit v2.0 wurde mit einer Reihen von Massnahmen der Speicherverbrauch reduziert:

* Minimierung der Anzahl interner Attribute
* Verwendung nativer Datentypen (soweit sinnvoll und möglich)
* Verwendung von PackedDecimal (soweit sinnvoll und möglich)
* Reduzierung von Duplikaten durch Einführung einer of-Methode zusammen mit Caching (s.u.).

Der minimale Footprint wird teilweise durch eine aufwendigere Objekt-Erzeugung oder/und Methoden-Zugriff erkauft.
Dies kann evtl. bei Massenverarbeitung zum Flaschenhals werden.
Hier kann man aber durch parallele Zugriffe entgegensteuern.

Damit sind Fachwerte auch für große Datenmengen geeignet, die im Hauptspeicher gehalten und parallel verarbeitet werden sollen.



==== of-Methode (valueOf)

Ursprünglich wurde auf eine statische `of`-Methode, wie sie seit Java 8 bei vielen Klassen aus dem JDK üblich ist (Beispiel: `LocalDate.of(jahr, monat, tag)`), bis v0.6 verzichtet,
weil statische Methoden von abgeleiteten Klassen nicht überschrieben werden können.
Mit der Einführung des math-Package in v0.6 wurde of bei einigen Klassen eine statische `of`-Methode aus folgenden Gründen eingeführt:
                   
* Die Anzahl (und Speicherverbrauch) lässt sich reduzieren, indem oft gebrauchte Werte "vorgehalten" werden.
* erhöhte Lesbarkeit

Dies lohnt sich vor allem für Objekte, die immer den gleichen Werte oder nur einige Werte haben (z.B. Rechnungsmonat).
Dies kann bei sehr vielen Objekten einen spürbaren Rückgang des Speicherverbraucs bedeuten.

Bei Klassen, die Ähnlichkeiten zur Number-Klasse haben (wie z.B. Geldbetrag), wird zusätzlich zur of-Methode eine valueOf-Methode bereitgestellt, analog zur valueOf-Methode der Number-Klasse.



==== Caching

Mit v1.2 wurde für alle wichtigen Klassen in interner Cache eingeführt, in dem erzeugte Objekte abgelegt werden.
Dies dient vor allem zur Reduktion des Speicherbedarfs.
Dies wird über die `of(..)`-Methode gesteuert.

Damit die Cache-Verwaltung selber nicht zu Speicherproblemen führt, wurde dazu eine `WeakHashMap` verwendet.
Von daher werden Duplikate zwar reduziert, können aber auch nicht ganz ausgeschlossen werden.
 


=== Gleichheit

Die equals- und hashCode-Methode wurden jeweils überschrieben.
Zwei Fachwerte sind gleich, wenn sie jeweils die gleichen Werte besitzen.

Bei Klassen im post-Paket findet ein fachlicher Vergleich statt (ab v2.1).
So werden bei der Adresse "Göthestraße", "Goethestrasse" und "Göthestr." jeweils als die gleiche Straße angesehen.
Möchte man es exakt, gibt es in diesen Klasse eine `equalsExact(..)`-Methode.


=== toString

Jeder Fachwert hat eine aussagekräftige `toString`-Implementierung.
Meist ist dies der Wert selbst.



=== Eigene Money-Klasse (Geldbetrag)

Mit 1.0 kam die Geldbetrag-Klasse hinzu, die das MonetaryAmount-Interface aus "javax.money" implementiert.
Gründe für eine eigene Implementierung waren:

* Der Umgang mit dem Package "javax.money" und das Anlegen von MonetaryAmount-Objekten ist manchmal etwas sperrig.
  Ziel war es, den Umgang möglichst einfach, zumindestens aber so einfach wie der Umgang mit BigDicimal-Beträgen zu machen.
  D.h. das Erzeugen eines Geldbetrags sollte auch über Konstruktoren möglich sein.
* Für Sonderfälle sollte es möglich sein, das Default-Verhalten einer MonetaryAmount-Klasse zu überschreiben.
  Dies ist mit der http://javamoney.github.io/ri.html[Referenz-Implementierung] leider nicht möglich, da die Klassen 'final' sind.
* Die Geldbetrag sollte als Alternative zur BigDecimal-Klasse eingesetzt werden können.
  Dies ist vor allem für die Portierung älterer Anwendungen gedacht, die noch mit BigDecimal arbeiten.

Der letzte Punkt ist auch der Grund, warum die Geldbetrag-Klasse zusätzlich zur of(..)-Methoden auch valueOf(..)-Methoden besitzen.
Dabei werden die gleichen Parameter wie bei BigDecimal akzeptiert.


==== JSR 354 - Technical Compatibiliy Kit (TCK)

Auf GitHub gibt es unter https://github.com/JavaMoney/jsr354-tck[JavaMoney/jsr354-tck] ein TCK, das zur Verifizierung der korrekten Implementierung herangeogen wird.
Resultat des TCKs war u.a. die `GeldbetragFactory`-Klasse, aber auch andere Klassen, die nur für den internen Gebrauch gedacht sind und dementsprechend auch unter `de.jfachwert.bank.internal` abgelegt wurden.
Aufgerufen wird das TCK über den Integrationstest `GeldbetragIT`.

Aktuell schlägt ein Test mit dem TCK fehl.
Dies betrifft den Vergleich zweier Geldbeträge mit unterschiedlichen Währungen mithilfe der compareTo-Methode.
Dazu gibt es unter https://github.com/JavaMoney/jsr354-tck/issues/18//[Issue #18] ein Bug-Report, da die verwendete omparable-Implementierung (s.u.) durch JSR 354 abgedeckt ist.


==== Operatoren

Alle Operatoren geben einen Geldbetrag zurück, da die Klasse selbst immutable ist.
Um die Erzeugung neuer Objekte zu minimieren, wird der Geldbetrag selbst zurueckgegeben, falls dies moeglich ist (z.B. beim Absolutbetrag, wenn der Geldbetrag bereits positiv ist).

Bei Operatoren, die einen Geldbetrag als Operand erwarten (z.B. Addition), müssen die Währungen übereinstimmen.
Ansonsten wird eine `MonetaryException` geworfen.
Ausnahmen hiervon sind neutrale Operanden wie z.B. die Addtion oder Subtraktion von 0 EUR.
Da dies den Wert eines Geldbetrags nicht ändert, wird hier die Währung ignoriert und _keine_ MonetaryException ausgelöst.


==== Comparable-Implementierung

Die Comparable-Implementierung zweier Geldbeträge B1 und B2 richtet sich nach folgendem Schema:

* gleiche Währung, B1 > B2: compareTo liefert Wert > 0
* ungleiche Währung, B1 = 0, B2 > 0: compareTo liefert Wert < 0
* ungleiche Währung, B1 != 0, B2 != 0: MonetaryException wird geworfen.

Wenn einer der Operatoren 0 ist, spielt die Währung für den Vergleich keine Rolle.
Ansonsten muss die Währung übereinstimmen.

Dies gilt auch für die Implementierung der equals-Methode:
zwei 0-Beträge werden als gleich angesehen, auch wenn sie unterschiedliche Währungseinheiten besitzen.


=== Kompatiblität der Kotlin-Portierung (v4)

Wegen https://youtrack.jetbrains.com/issue/KT-6653[KT-6653] ist das Kotlin Interface _ILocalizedException_ nicht identisch zur Java-Variante _LocalizedException_.
Da dieses Interface aber nur für den internen Gebrauch gedacht ist, wurde diese Inkompatibilität in Kauf genommen.

Einige weitere Interfaces wie _Fachwert_ sind in Java verblieben, da Interfaces mit Default-Implementierung nicht 100%-ig kompatibel sind (s. https://youtrack.jetbrains.com/issue/KT-4779[KT-4779]).
Für die Verwendung in Kotlin gibt es das Interface mit vorangestelltem 'K' (_KFachwert_).

Ansosten wird die Kompatilität zur Java Version (v3) dadurch sichergestellt, das die Unit-Tests in Java verbleiben und auch in Java weiterentwickelt werden.
Daneben wurden einige Klassen aus anderen Projekte, bei denen es Kompatibiltätsprobleme gab, als zusätzliche Testfälle hinzugefügt.