@startuml

folder "commons" {

    [commons-lang3.jar]

}

[jfachwert.jar] ..> commons

[jfachwert.jar] ..> [kotlin-stdlib.jar]

[jfachwert.jar] ..> [money-api.jar]

[commons-lang3.jar] #White
[kotlin-stdlib.jar] #White
[money-api.jar] #Lightgrey

@enduml
