@startuml

package "med" {

    class IK
    class LANR
    class BSNR
    class Hilfsmittelnummer
    class PZN
    class SNOMED
    class Versichertennummer
    class ZANR

    LANR <|-- ZANR

}

@enduml
