@startuml

package "de.jfachwert.money" {

    class GeldbetragFactory
    class Waehrung
    class Geldbetrag

}

class javax.money.MonetaryContext #white
interface javax.money.CurrencyUnit #white
interface javax.money.MonetaryAmountFactory #white
interface javax.money.MonetaryAmount #white

javax.money.MonetaryAmount <|.. Geldbetrag
javax.money.CurrencyUnit <|.. Waehrung
javax.money.MonetaryAmountFactory <|.. GeldbetragFactory

GeldbetragFactory --> Geldbetrag
Geldbetrag -- javax.money.MonetaryContext
Geldbetrag -- Waehrung

@enduml
