@startuml

package "jfachwert" {

    package "zeit" {
    }

    package "med" {
    }

    package "math" {
    }

    package "net" {
    }

    package "steuer" {
    }

    package "post" {
    }

    package "rechnung" {
    }

    package "formular" {
    }

    package "money" {
    }

    package "bank" {
    }

    package "validation" {
    }

    frame "core" {
        package "util" {
        }
        package "pruefung" {
        }
    }

    bank ..> pruefung
    money ..> pruefung
    formular ..> pruefung
    steuer ..> pruefung
    post ..> pruefung
    rechnung ..> pruefung
    net ..> pruefung
    med ..> pruefung
    math ..> pruefung
    zeit ..> pruefung
    validation ..> pruefung

}

@enduml