@startuml

package "de.fachwert.bank" {

    class Kontonummer
    class IBAN
    class BLZ
    class BIC
    class Bankverbindung
    class Geldbetrag
    class GeldbetragFactory
    class Waehrung
    class Zinssatz

}

interface javax.money.MonetaryAmount #white

javax.money.MonetaryAmount <|.. Geldbetrag
Geldbetrag -- Waehrung
GeldbetragFactory .. Geldbetrag
GeldbetragFactory .. Waehrung

@enduml
