@startuml

package "jfachwert" {

    package "util" {
    }

    package "med" {
    }

    package "math" {
    }

    package "net" {
    }

    package "steuer" {
    }

    package "post" {
    }

    package "rechnung" {
    }

    package "formular" {
    }

    package "bank" {
    }

    package "pruefung" {
    }

    bank ..> pruefung
    formular ..> pruefung
    steuer ..> pruefung
    post ..> pruefung
    rechnung ..> pruefung
    net ..> pruefung
    med ..> pruefung
    math ..> pruefung

}

@enduml